name: Release

on:
  push:
    branches:
      - main

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Git user
        run: |
          git config --global user.name 'Tramvai Conductor'
          git config --global user.email 'tramvai-conductor@users.noreply.github.com'

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TRAMVAI_GH_PAGES_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
